### PR TITLE
Create tr_TR.lang

### PR DESCRIPTION
**Pull request by Emirhangg**
Made by: Emirhangg
Turkish Language.

### CODE REVIEW

**Comment by Emirhangg** [comment]
Words are not broken :) . I tried and it works perfectly.

**Comment by a3626a** [comment]
Thank you for your contribution.
This change will be included in following update (5.4.3.0) within a few days.

**Comment by a3626a** [comment]
After looking into your .lang file and several encodings, I am sure that your .lang file is broken.

When I read your .lang file using UTF-8 (Minecraft or Forge uses this encoding),
```
tile.hungryanimals.excreta.name=DÄ±ÅŸkÄ±
```
and I guess proper translation is (using google)
```
tile.hungryanimals.excreta.name=Dışkı
```
So, `ı` is miss-coded into `Ä±`, `ş` into `ÅŸ`.

One scenario for this miss-coding is, you wrote .lang in UTF-8,
`dışkı` -> `44 c4 b1 c5 9f 6b c4 b1`
 open it in windows-1252/latin1,
 `44 c4 b1 c5 9f 6b c4 b1` -> `DÄ±ÅŸkÄ±`
and save it in UTF-8.
`DÄ±ÅŸkÄ±` -> `44 c3 84 c2 b1 c3 85 c5 b8 6b c3 84 c2 b1`

Can you double check your encoding?

**Comment by a3626a** [comment]
In my case, it is displayed as `DÄ±ÅŸkÄ±` in Minecraft, too.

and your .lang file looks at GitHub :
image

**Comment by Emirhangg** [comment]
Yes, in all Turkish translations, the characters looks like broken. But works with no problems in the game. And you can try in-game.  😊

**Comment by a3626a** [comment]
It looks like this for me

image

**Comment by Emirhangg** [comment]
Can you upload your .lang file?

**Comment by a3626a** [comment]
https://www.dropbox.com/s/t3z1f04wijoekbj/tr_TR.lang?dl=0

**Comment by Emirhangg** [comment]
It looks like this file is broken, but when I test from github, it works.
Original file : [https://drive.google.com/open?id=1tsmZvqyc-uC9_EtQlR-dMxyqJhGIj9fN](url)

**Comment by a3626a** [comment]
That file is perfect. I will update it.

**Comment by a3626a** [comment]
4cd1475601d483e3fecdd78f866a77644e02c4e4

**Pull request merged**
